In [1]:
import numpy as np


In [24]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a.shape

(2, 7)

In [27]:
#Obtenir un élément particulier [row, col]
a[1, 5]
#a[1, -2] fonctionne aussi

13

In [30]:
#Obtenir une ligne spécifique
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#Obtenir une colonne spécifique
a[:, 4]

array([ 5, 12])

In [33]:
#Obtenir une partie de la ligne [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [34]:
a[1, 5] = 20

In [37]:
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [38]:
#Exemple 3D
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
#Obtenir un élément particulier
#b[0, 1, 1]
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [45]:
#Remplacer
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])