In [1]:
import numpy as np


In [48]:
#initialiser tout à 0
#np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
#Initialiser tout à 1
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [51]:
#Autres nombres
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [54]:
#Autres nombres (full_like methode)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
#Nombres décimaux aléatoires
#np.random.rand(4,2,3)
np.random.random_sample(a.shape)

array([[0.15153203, 0.77346532, 0.05444551, 0.07168253, 0.78586176,
        0.75336862, 0.12375756],
       [0.42203689, 0.55937425, 0.04303002, 0.21411449, 0.66840147,
        0.47335173, 0.85679145]])

In [61]:
#Valeurs Int aléatoires
np.random.randint(4,7, size=(3,3))

array([[5, 6, 5],
       [4, 6, 4],
       [4, 5, 4]])

In [63]:
#Matrice identité
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
#Répétition d'un tableau
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
# ATTENTION !!!
a = np.array([1,2,3])
b = a
b[0]=100
print(a) #modif aussi dans a alors que l'on veut que dans b
print(b)

[100   2   3]
[100   2   3]


In [78]:
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)
print(b) #modif que dans b

[1 2 3]
[100   2   3]
