In [1]:
import numpy as np

# **Mathématiques**

In [95]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [90]:
a + 2

array([3, 4, 5, 6])

In [91]:
a - 2

array([-1,  0,  1,  2])

In [92]:
a * 2

array([2, 4, 6, 8])

In [93]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [96]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [97]:
a ** 2

array([ 1,  4,  9, 16])

In [99]:
#Sin
np.sin(a)

#Cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## **Algèbre Linéaire**

In [102]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [103]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [104]:
#Trouver le déterminant
c = np.identity(3)
np.linalg.det(c)

1.0

### **Statistiques**

In [105]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.min(stats)
#np.min(stats, axis=1)

1

In [107]:
np.max(stats)

6

In [114]:
np.sum(stats)


21

In [115]:
np.sum(stats, axis=0)

array([5, 7, 9])

# **Réorganiser des tableaux**

In [119]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [120]:
#Stack vecteurs verticalement
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
#Stack vecteurs horizontalement
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])