In [1]:
import numpy as np


In [16]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Obtenir la dimension d'un array
b.ndim

2

In [7]:
#Obtenir la forme
b.shape

(2, 3)

In [19]:
#Obtenir le type
a.dtype



dtype('int32')

In [20]:
#Obtenir la taille
a.itemsize

4

In [23]:
#Obtenir la taille totale (nb total d'éléments)
#a.size
#a.size * a.itemsize
a.nbytes

12